apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: lab5-app
  labels:
    app: hello-app
    app.kubernetes.io/part-of: lab-5-base
spec:
  type: ClusterIP
  selector:
    app: hello-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: metrics
      protocol: TCP
      port: 9113
      targetPort: metrics
