fullnameOverride: kube-prometheus-stack

prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    retention: 12h
    scrapeInterval: 15s
    evaluationInterval: 15s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    resources:
      requests:
        cpu: 200m
        memory: 600Mi
      limits:
        cpu: 600m
        memory: 1Gi

alertmanager:
  service:
    type: ClusterIP
  alertmanagerSpec:
    configSecret: alertmanager-telegram-config
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi

grafana:
  adminUser: admin
  adminPassword: admin
  service:
    type: ClusterIP
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
      label: grafana_dashboard
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 80m
      memory: 120Mi
    limits:
      cpu: 300m
      memory: 300Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 30m
      memory: 60Mi
    limits:
      cpu: 120m
      memory: 180Mi
